#!/bin/bash

echo "🚨 API密钥泄漏清理脚本"
echo "========================"
echo ""
echo "⚠️  警告: 这将重写Git历史，确保你明白这个操作的后果！"
echo ""
echo "步骤 1: 请立即到 OpenAI 平台撤销泄漏的API密钥"
echo "步骤 2: 生成新的API密钥"
echo "步骤 3: 运行以下命令清理Git历史"
echo ""
echo "# 方法1: 使用 BFG Repo-Cleaner (推荐)"
echo "# 首先安装: brew install bfg"
echo "# 然后运行:"
echo "bfg --replace-text <(echo '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===>***REMOVED***')"
echo "git reflog expire --expire=now --all && git gc --prune=now --aggressive"
echo ""
echo "# 方法2: 重置到安全的提交点"
echo "git reset --hard d03282c  # 重置到泄漏前的提交"
echo "# 然后重新应用安全的更改"
echo ""
echo "# 方法3: 强制推送覆盖远程历史 (危险)"
echo "git push --force-with-lease origin main"
echo ""
echo "🔐 完成后记得:"
echo "1. 设置新的API密钥到环境变量"
echo "2. 验证.env文件不包含真实密钥"
echo "3. 确认.gitignore包含.env"